### ISSUE TITLE
How to run the programme

### ISSUE THREAD

**Issue by bricsek** [windkh/FroniusReader#3]
Hello!
I have downloaded the .zip file, and already exctracted it, but i don't know how to sart/run it. Can you tell me how can i run the programme?

**Comment by windkh** [comment]
Double click the exe file

**Comment by bricsek** [comment]
Where can I find the exe file?

**Comment by windkh** [comment]
![image](https://user-images.githubusercontent.com/10910767/227768585-5a72115c-77b8-4f7d-86c7-3c96e0ce1724.png)

**Comment by windkh** [comment]
https://github.com/windkh/FroniusReader/releases

[FroniusReader.zip](https://github.com/windkh/FroniusReader/releases/download/V0.1.0/FroniusReader.zip)

**Comment by bricsek** [comment]
I tried to run the exe on win 11, 8.1 and 7 but when i launched it othing happened. I already tried to run it as administartor but still nothing. Can you give me an adviece what could be the problem? Sorry that i'm don't understand it but i wolud really like to use it. 
Thanks for your help!

**Comment by windkh** [comment]
Hm it only uses the net framework 4, nothing else.
Maybe you can check if it is installed

**Comment by windkh** [comment]
If it does not help we can arrange a teams meeting

**Comment by bricsek** [comment]
Yes, I have framework 4 installed and still does not work. I would be really happy if we could discuss this. Can you give me an appointment and a contact for this?

**Comment by windkh** [comment]
@bricsek hi, I will have time after 9pm today or maybe on wednesday if that is not too late for you.
You can send me a private mail under karl-heinz.wind@web.de

**Comment by windkh** [comment]
@bricsek maybe you try again with that one before we start a teams meeting.
https://github.com/windkh/FroniusReader/releases/tag/V0.2.0

I made some improvements about stability.
When the application starts you need to enter the IP Address or Host-Name in the top left field.
Please let me know if it worked

**Comment by bricsek** [comment]
It worked! Thanks a lot! Have a nice day!

**Comment by windkh** [comment]
Nice ... remember that this tool was done in a hurry. If you have any questions you are welcome
